In [7]:
# CyberShield Analytics
## ETL & Dataset Analysis
"Proyecto de análisis de ataques de ciberseguridad utilizando arquitectura Data Lakehouse."

'Proyecto de análisis de ataques de ciberseguridad utilizando arquitectura Data Lakehouse.'

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('../data/raw/cybersecurity_attacks.csv')

In [5]:
df.head()

,Timestamp,Source IP Address,Destination IP Address,Source Port,Destination Port,Protocol,Packet Length,Packet Type,Traffic Type,Payload Data,...,Action Taken,Severity Level,User Information,Device Information,Network Segment,Geo-location Data,Proxy Information,Firewall Logs,IDS/IPS Alerts,Log Source
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Logged,Low,Reyansh Dugal,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Blocked,Low,Sumer Rana,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Ignored,Low,Himmat Karpe,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Blocked,Medium,Fateh Kibe,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Blocked,Low,Dhanush Chad,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Timestamp               40000 non-null  str
 1   Source IP Address       40000 non-null  str
 2   Destination IP Address  40000 non-null  str
 3   Source Port             40000 non-null  int64
 4   Destination Port        40000 non-null  int64
 5   Protocol                40000 non-null  str
 6   Packet Length           40000 non-null  int64
 7   Packet Type             40000 non-null  str
 8   Traffic Type            40000 non-null  str
 9   Payload Data            40000 non-null  str
 10  Malware Indicators      20000 non-null  str
 11  Anomaly Scores          40000 non-null  float64
 12  Alerts/Warnings         19933 non-null  str
 13  Attack Type             40000 non-null  str
 14  Attack Signature        40000 non-null  str
 15  Action Taken            40000 non-null  str
 16  Severity Level          40000 non-null  str
 17  User Information        40000 non-null  str
 18  Device Information      40000 non-null  str
 19  Network Segment         40000 non-null  str
 20  Geo-location Data       40000 non-null  str
 21  Proxy Information       20149 non-null  str
 22  Firewall Logs           20039 non-null  str
 23  IDS/IPS Alerts          19950 non-null  str
 24  Log Source              40000 non-null  str
dtypes: float64(1), int64(3), str(21)
memory usage: 22.9 MB

In [9]:
df.columns

Index(['Timestamp', 'Source IP Address', 'Destination IP Address',
       'Source Port', 'Destination Port', 'Protocol', 'Packet Length',
       'Packet Type', 'Traffic Type', 'Payload Data', 'Malware Indicators',
       'Anomaly Scores', 'Alerts/Warnings', 'Attack Type', 'Attack Signature',
       'Action Taken', 'Severity Level', 'User Information',
       'Device Information', 'Network Segment', 'Geo-location Data',
       'Proxy Information', 'Firewall Logs', 'IDS/IPS Alerts', 'Log Source'],
      dtype='str')

In [10]:
df.isnull().sum()

Timestamp                     0
Source IP Address             0
Destination IP Address        0
Source Port                   0
Destination Port              0
Protocol                      0
Packet Length                 0
Packet Type                   0
Traffic Type                  0
Payload Data                  0
Malware Indicators        20000
Anomaly Scores                0
Alerts/Warnings           20067
Attack Type                   0
Attack Signature              0
Action Taken                  0
Severity Level                0
User Information              0
Device Information            0
Network Segment               0
Geo-location Data             0
Proxy Information         19851
Firewall Logs             19961
IDS/IPS Alerts            20050
Log Source                    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['Geo-location Data'].head(20)

0           Jamshedpur, Sikkim
1           Bilaspur, Nagaland
2            Bokaro, Rajasthan
3           Jaunpur, Rajasthan
4           Anantapur, Tripura
5        Aurangabad, Meghalaya
6               Eluru, Manipur
7     Phagwara, Andhra Pradesh
8              Ambala, Tripura
9              Rampur, Mizoram
10            Gangtok, Haryana
11            Nandyal, Mizoram
12             Silchar, Kerala
13            Gudivada, Odisha
14        Silchar, Maharashtra
15           Bhiwandi, Tripura
16          Solapur, Telangana
17          Darbhanga, Mizoram
18           Rampur, Rajasthan
19     Ahmednagar, Uttarakhand
Name: Geo-location Data, dtype: str

In [13]:
df['Geo-location Data'].unique()[:20]

<ArrowStringArray>
[      'Jamshedpur, Sikkim',       'Bilaspur, Nagaland',
        'Bokaro, Rajasthan',       'Jaunpur, Rajasthan',
       'Anantapur, Tripura',    'Aurangabad, Meghalaya',
           'Eluru, Manipur', 'Phagwara, Andhra Pradesh',
          'Ambala, Tripura',          'Rampur, Mizoram',
         'Gangtok, Haryana',         'Nandyal, Mizoram',
          'Silchar, Kerala',         'Gudivada, Odisha',
     'Silchar, Maharashtra',        'Bhiwandi, Tripura',
       'Solapur, Telangana',       'Darbhanga, Mizoram',
        'Rampur, Rajasthan',  'Ahmednagar, Uttarakhand']
Length: 20, dtype: str

In [14]:
df['Geo-location Data'].value_counts().head(20)

Geo-location Data
Ghaziabad, Meghalaya                       16
Kalyan-Dombivli, Jharkhand                 15
Ghaziabad, Tripura                         14
Ghaziabad, Uttarakhand                     14
Ghaziabad, Jharkhand                       13
Srikakulam, Uttarakhand                    13
Motihari, Odisha                           13
Aurangabad, Nagaland                       13
Kottayam, Nagaland                         13
Amroha, Sikkim                             13
Yamunanagar, Arunachal Pradesh             13
Ichalkaranji, Sikkim                       12
Kanpur, Goa                                12
Jalna, Andhra Pradesh                      12
Rampur, Gujarat                            12
Bally, Maharashtra                         12
Raurkela Industrial Township, Jharkhand    12
Ghaziabad, Nagaland                        12
Aurangabad, Odisha                         12
Ghaziabad, Odisha                          12
Name: count, dtype: int64

In [15]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('/', '_')
    .str.replace('-', '_')
)

In [16]:
df.columns

Index(['timestamp', 'source_ip_address', 'destination_ip_address',
       'source_port', 'destination_port', 'protocol', 'packet_length',
       'packet_type', 'traffic_type', 'payload_data', 'malware_indicators',
       'anomaly_scores', 'alerts_warnings', 'attack_type', 'attack_signature',
       'action_taken', 'severity_level', 'user_information',
       'device_information', 'network_segment', 'geo_location_data',
       'proxy_information', 'firewall_logs', 'ids_ips_alerts', 'log_source'],
      dtype='str')

In [17]:
# Estrategia de tratamiento de valores nulos
"Las columnas relacionadas con alertas, malware y proxies contienen valores nulos que pueden representar ausencia de eventos de seguridad, por lo que inicialmente no serán eliminadas."

'Las columnas relacionadas con alertas, malware y proxies contienen valores nulos que pueden representar ausencia de eventos de seguridad, por lo que inicialmente no serán eliminadas.'

In [18]:
df_clean = df.copy()

In [19]:
df_clean.shape

(40000, 25)

In [20]:
india_regions = (
    df_clean['geo_location_data']
    .str.split(',')
    .str[-1]
    .str.strip()
)

In [21]:
india_regions.unique()[:30]

array(['Sikkim', 'Nagaland', 'Rajasthan', 'Tripura', 'Meghalaya',
       'Manipur', 'Andhra Pradesh', 'Mizoram', 'Haryana', 'Kerala',
       'Odisha', 'Maharashtra', 'Telangana', 'Uttarakhand', 'West Bengal',
       'Gujarat', 'Chhattisgarh', 'Assam', 'Madhya Pradesh', 'Karnataka',
       'Goa', 'Tamil Nadu', 'Uttar Pradesh', 'Bihar', 'Himachal Pradesh',
       'Arunachal Pradesh', 'Jharkhand', 'Punjab'], dtype=object)

In [22]:
india_regions.value_counts()

geo_location_data
Manipur              1498
Uttar Pradesh        1485
Gujarat              1483
Maharashtra          1474
Arunachal Pradesh    1472
Karnataka            1467
West Bengal          1465
Bihar                1462
Rajasthan            1460
Uttarakhand          1441
Haryana              1440
Nagaland             1439
Mizoram              1438
Jharkhand            1437
Kerala               1416
Sikkim               1410
Odisha               1410
Assam                1404
Meghalaya            1403
Chhattisgarh         1400
Andhra Pradesh       1399
Goa                  1399
Telangana            1393
Tamil Nadu           1393
Himachal Pradesh     1384
Tripura              1381
Punjab               1374
Madhya Pradesh       1373
Name: count, dtype: int64

In [23]:
mexico_states = [
    'Ciudad de México',
    'Jalisco',
    'Nuevo León',
    'Puebla',
    'Querétaro',
    'Yucatán',
    'Chihuahua',
    'Guanajuato',
    'Veracruz',
    'Baja California',
    'Sonora',
    'Coahuila',
    'Tamaulipas',
    'Michoacán',
    'Oaxaca',
    'Sinaloa',
    'Durango',
    'San Luis Potosí',
    'Aguascalientes',
    'Zacatecas'
]

In [24]:
india_unique = india_regions.unique()

mapping_dict = {}

for i, region in enumerate(india_unique):
    mapping_dict[region] = mexico_states[i % len(mexico_states)]

In [25]:
list(mapping_dict.items())[:20]

[('Sikkim', 'Ciudad de México'),
 ('Nagaland', 'Jalisco'),
 ('Rajasthan', 'Nuevo León'),
 ('Tripura', 'Puebla'),
 ('Meghalaya', 'Querétaro'),
 ('Manipur', 'Yucatán'),
 ('Andhra Pradesh', 'Chihuahua'),
 ('Mizoram', 'Guanajuato'),
 ('Haryana', 'Veracruz'),
 ('Kerala', 'Baja California'),
 ('Odisha', 'Sonora'),
 ('Maharashtra', 'Coahuila'),
 ('Telangana', 'Tamaulipas'),
 ('Uttarakhand', 'Michoacán'),
 ('West Bengal', 'Oaxaca'),
 ('Gujarat', 'Sinaloa'),
 ('Chhattisgarh', 'Durango'),
 ('Assam', 'San Luis Potosí'),
 ('Madhya Pradesh', 'Aguascalientes'),
 ('Karnataka', 'Zacatecas')]

In [26]:
df_clean['mexico_state'] = india_regions.map(mapping_dict)

In [27]:
df_clean[['geo_location_data', 'mexico_state']].head(20)

           geo_location_data      mexico_state
0         Jamshedpur, Sikkim  Ciudad de México
1         Bilaspur, Nagaland           Jalisco
2          Bokaro, Rajasthan        Nuevo León
3         Jaunpur, Rajasthan        Nuevo León
4         Anantapur, Tripura            Puebla
5      Aurangabad, Meghalaya         Querétaro
6             Eluru, Manipur           Yucatán
7   Phagwara, Andhra Pradesh         Chihuahua
8            Ambala, Tripura            Puebla
9            Rampur, Mizoram        Guanajuato
10          Gangtok, Haryana          Veracruz
11          Nandyal, Mizoram        Guanajuato
12           Silchar, Kerala   Baja California
13          Gudivada, Odisha            Sonora
14      Silchar, Maharashtra          Coahuila
15         Bhiwandi, Tripura            Puebla
16        Solapur, Telangana        Tamaulipas
17        Darbhanga, Mizoram        Guanajuato
18         Rampur, Rajasthan        Nuevo León
19   Ahmednagar, Uttarakhand         Michoacán

In [28]:
df_clean['mexico_state'].isnull().sum()

np.int64(0)

In [30]:
# Transformación Geográfica India → México

'Se implementó una estrategia de regionalización para contextualizar el dataset original de India hacia entidades geográficas mexicanas, permitiendo análisis espaciales y dashboards orientados al contexto nacional.'

'Se implementó una estrategia de regionalización para contextualizar el dataset original de India hacia entidades geográficas mexicanas, permitiendo análisis espaciales y dashboards orientados al contexto nacional.'

In [31]:
mexico_coordinates = {
    'Ciudad de México': (19.4326, -99.1332),
    'Jalisco': (20.6597, -103.3496),
    'Nuevo León': (25.6866, -100.3161),
    'Puebla': (19.0414, -98.2063),
    'Querétaro': (20.5888, -100.3899),
    'Yucatán': (20.9674, -89.5926),
    'Chihuahua': (28.6329, -106.0691),
    'Guanajuato': (21.0190, -101.2574),
    'Veracruz': (19.1738, -96.1342),
    'Baja California': (32.5149, -117.0382),
    'Sonora': (29.0729, -110.9559),
    'Coahuila': (25.4267, -100.9954),
    'Tamaulipas': (23.7369, -99.1411),
    'Michoacán': (19.7008, -101.1844),
    'Oaxaca': (17.0732, -96.7266),
    'Sinaloa': (24.8091, -107.3940),
    'Durango': (24.0277, -104.6532),
    'San Luis Potosí': (22.1565, -100.9855),
    'Aguascalientes': (21.8853, -102.2916),
    'Zacatecas': (22.7709, -102.5832)
}

In [32]:
df_clean['latitude'] = df_clean['mexico_state'].map(
    lambda x: mexico_coordinates[x][0]
)

df_clean['longitude'] = df_clean['mexico_state'].map(
    lambda x: mexico_coordinates[x][1]
)

In [33]:
df_clean[['mexico_state', 'latitude', 'longitude']].head(20)

        mexico_state  latitude  longitude
0   Ciudad de México   19.4326   -99.1332
1            Jalisco   20.6597  -103.3496
2         Nuevo León   25.6866  -100.3161
3         Nuevo León   25.6866  -100.3161
4             Puebla   19.0414   -98.2063
5          Querétaro   20.5888  -100.3899
6            Yucatán   20.9674   -89.5926
7          Chihuahua   28.6329  -106.0691
8             Puebla   19.0414   -98.2063
9         Guanajuato   21.0190  -101.2574
10          Veracruz   19.1738   -96.1342
11        Guanajuato   21.0190  -101.2574
12   Baja California   32.5149  -117.0382
13            Sonora   29.0729  -110.9559
14          Coahuila   25.4267  -100.9954
15            Puebla   19.0414   -98.2063
16        Tamaulipas   23.7369   -99.1411
17        Guanajuato   21.0190  -101.2574
18        Nuevo León   25.6866  -100.3161
19         Michoacán   19.7008  -101.1844

In [34]:
df_clean[['latitude', 'longitude']].isnull().sum()

latitude     0
longitude    0
dtype: int64

In [35]:
import geopandas as gpd
from shapely.geometry import Point

In [36]:
geometry = [
    Point(xy)
    for xy in zip(df_clean['longitude'], df_clean['latitude'])
]

In [37]:
gdf = gpd.GeoDataFrame(
    df_clean,
    geometry=geometry,
    crs='EPSG:4326'
)

In [38]:
gdf.head()

,timestamp,source_ip_address,destination_ip_address,source_port,destination_port,protocol,packet_length,packet_type,traffic_type,payload_data,...,network_segment,geo_location_data,proxy_information,firewall_logs,ids_ips_alerts,log_source,mexico_state,latitude,longitude,geometry
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server,Ciudad de México,19.4326,-99.1332,POINT (-99.1332 19.4326)
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall,Jalisco,20.6597,-103.3496,POINT (-103.3496 20.6597)
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall,Nuevo León,25.6866,-100.3161,POINT (-100.3161 25.6866)
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall,Nuevo León,25.6866,-100.3161,POINT (-100.3161 25.6866)
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall,Puebla,19.0414,-98.2063,POINT (-98.2063 19.0414)

In [39]:
gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [40]:
df_clean.to_parquet(
    '../data/clean/cybersecurity_attacks_clean.parquet',
    index=False
)

In [41]:
parquet_df = pd.read_parquet(
    '../data/clean/cybersecurity_attacks_clean.parquet'
)

parquet_df.head()

,timestamp,source_ip_address,destination_ip_address,source_port,destination_port,protocol,packet_length,packet_type,traffic_type,payload_data,...,device_information,network_segment,geo_location_data,proxy_information,firewall_logs,ids_ips_alerts,log_source,mexico_state,latitude,longitude
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server,Ciudad de México,19.4326,-99.1332
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall,Jalisco,20.6597,-103.3496
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall,Nuevo León,25.6866,-100.3161
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall,Nuevo León,25.6866,-100.3161
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall,Puebla,19.0414,-98.2063

In [42]:
gdf.to_parquet(
    '../data/geoparquet/cybersecurity_attacks_geospatial.parquet',
    index=False
)

In [43]:
gdf_validation = gpd.read_parquet(
    '../data/geoparquet/cybersecurity_attacks_geospatial.parquet'
)

gdf_validation.head()

,timestamp,source_ip_address,destination_ip_address,source_port,destination_port,protocol,packet_length,packet_type,traffic_type,payload_data,...,network_segment,geo_location_data,proxy_information,firewall_logs,ids_ips_alerts,log_source,mexico_state,latitude,longitude,geometry
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server,Ciudad de México,19.4326,-99.1332,POINT (-99.1332 19.4326)
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall,Jalisco,20.6597,-103.3496,POINT (-103.3496 20.6597)
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall,Nuevo León,25.6866,-100.3161,POINT (-100.3161 25.6866)
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall,Nuevo León,25.6866,-100.3161,POINT (-100.3161 25.6866)
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall,Puebla,19.0414,-98.2063,POINT (-98.2063 19.0414)

In [44]:
gdf_validation.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [47]:
# Exportación Data Lakehouse

"Se generó la capa CLEAN utilizando formato Parquet optimizado para procesamiento analítico y Machine Learning. Asimismo, se construyó un GeoParquet geoespacial compatible con herramientas GIS y dashboards geográficos."

'Se generó la capa CLEAN utilizando formato Parquet optimizado para procesamiento analítico y Machine Learning. Asimismo, se construyó un GeoParquet geoespacial compatible con herramientas GIS y dashboards geográficos.'